name: Pipeline

on:
  push:
    branches:
      - 'main'
      - 'feature**'
  delete:
    branches:
      - 'feature**'

env:
  PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SAM_TEMPLATE: template.yaml
  PRIMARY_REGION: eu-west-1
  SECONDARY_REGION: eu-central-1
  HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - region: eu-central-1
            environment: primary
          - region: eu-west-1
            environment: secondary
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Build resources
        run: sam build --template ${SAM_TEMPLATE} --use-container

      - name: Deploy to ${{ matrix.environment }} region
        run: |
          sam deploy \
            --stack-name photoblogapp-${{ matrix.environment }} \
            --capabilities CAPABILITY_IAM \
            --region ${{ matrix.region }} \
            --resolve-s3 \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset \
            --parameter-overrides \
              Environment=${{ matrix.environment }} \
              PrimaryRegion=${PRIMARY_REGION} \
              SecondaryRegion=${SECONDARY_REGION} \
              HostedZoneId=${HOSTED_ZONE_ID}

      - name: Store API ID in Parameter Store
        run: |
          API_ID=$(aws cloudformation describe-stacks \
            --stack-name photoblogapp-${{ matrix.environment }} \
            --region ${{ matrix.region }} \
            --query 'Stacks[0].Outputs[?OutputKey==`ApiId`].OutputValue' \
            --output text)
          
          aws ssm put-parameter \
            --name "/photoblog/${{ matrix.environment }}/api-id" \
            --value "$API_ID" \
            --type String \
            --overwrite \
            --region ${{ matrix.region }}
